/**
 * 100 Original DSA Problems — seed data
 * Run with: npm run seed:dsa
 */
require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const mongoose  = require('mongoose');
const connectDB = require('../config/db');
const Problem   = require('../models/Problem');

/* ──────────────────────────────────────────
   HELPER — build a problem object
────────────────────────────────────────── */
const p = (order, title, difficulty, category, tags, desc, inputFmt, outputFmt,
           constraints, examples, starterCode, testCases, hiddenTestCases) => ({
  order, title,
  slug: title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''),
  difficulty, category, tags,
  description: desc,
  inputFormat: inputFmt,
  outputFormat: outputFmt,
  constraints,
  examples,
  starterCode,
  testCases,
  hiddenTestCases,
  timeLimit: difficulty === 'Hard' ? 3000 : difficulty === 'Medium' ? 2000 : 1000,
  memoryLimit: 256,
  isPublished: true,
});

/* ──────────────────────────────────────────
   STARTER CODE TEMPLATES
────────────────────────────────────────── */
const jsArr = (fn) => `function solution(nums) {\n    // ${fn}\n    \n}`;
const jsTwoArr = (fn) => `function solution(nums, target) {\n    // ${fn}\n    \n}`;
const jsStr = (fn) => `function solution(s) {\n    // ${fn}\n    \n}`;
const jsTwoStr = (fn) => `function solution(s, t) {\n    // ${fn}\n    \n}`;

const sc = (js, py = '', java = '', cpp = '') => ({ javascript: js, python: py, java, cpp });

/* ──────────────────────────────────────────
   THE 100 PROBLEMS
────────────────────────────────────────── */
const problems = [

/* ═══════════════════ EASY ARRAYS 1-10 ═══════════════════ */
p(1,'Two Sum','Easy','Arrays',['Array','Hash Table'],
`Given an array of integers \`nums\` and an integer \`target\`, return the **indices** of the two numbers that add up to \`target\`. You may not use the same element twice. Assume exactly one solution exists.`,
'First line: space-separated integers. Second line: target integer.',
'Two space-separated indices (0-based).',
'2 ≤ nums.length ≤ 10^4, -10^9 ≤ nums[i] ≤ 10^9',
[{input:'2 7 11 15\n9',output:'0 1',explanation:'nums[0]+nums[1]=9'},{input:'3 2 4\n6',output:'1 2',explanation:'nums[1]+nums[2]=6'}],
sc(jsTwoArr('use a hash map for O(n)')),
[{input:'2 7 11 15\n9',expectedOutput:'0 1'},{input:'3 2 4\n6',expectedOutput:'1 2'}],
[{input:'3 3\n6',expectedOutput:'0 1',isHidden:true},{input:'1 2 3 4 5\n9',expectedOutput:'3 4',isHidden:true},{input:'0 4 3 0\n0',expectedOutput:'0 3',isHidden:true}]),

p(2,'Maximum Subarray','Easy','Arrays',['Array','Dynamic Programming','Divide and Conquer'],
`Given an integer array \`nums\`, find the contiguous subarray with the **largest sum** and return the sum.`,
'Space-separated integers.',
'A single integer — the maximum subarray sum.',
'1 ≤ nums.length ≤ 10^5, -10^4 ≤ nums[i] ≤ 10^4',
[{input:'-2 1 -3 4 -1 2 1 -5 4',output:'6',explanation:'[4,-1,2,1] has sum 6'},{input:'1',output:'1'}],
sc(jsArr('Kadane\'s algorithm')),
[{input:'-2 1 -3 4 -1 2 1 -5 4',expectedOutput:'6'},{input:'1',expectedOutput:'1'}],
[{input:'5 4 -1 7 8',expectedOutput:'23',isHidden:true},{input:'-1',expectedOutput:'-1',isHidden:true},{input:'-2 -1',expectedOutput:'-1',isHidden:true}]),

p(3,'Contains Duplicate','Easy','Arrays',['Array','Hash Table','Sorting'],
`Given an integer array \`nums\`, return \`true\` if any value appears at least twice, or \`false\` if every element is distinct.`,
'Space-separated integers.','true or false.',
'1 ≤ nums.length ≤ 10^5',
[{input:'1 2 3 1',output:'true'},{input:'1 2 3 4',output:'false'}],
sc(jsArr('use a Set')),
[{input:'1 2 3 1',expectedOutput:'true'},{input:'1 2 3 4',expectedOutput:'false'}],
[{input:'1 1 1 3 3 4 3 2 4 2',expectedOutput:'true',isHidden:true},{input:'5',expectedOutput:'false',isHidden:true}]),

p(4,'Move Zeroes','Easy','Arrays',['Array','Two Pointers'],
`Given an array \`nums\`, move all \`0\`s to the end while maintaining the relative order of the non-zero elements. Modify in-place.`,
'Space-separated integers.','Space-separated integers after moving zeroes.',
'1 ≤ nums.length ≤ 10^4',
[{input:'0 1 0 3 12',output:'1 3 12 0 0'},{input:'0',output:'0'}],
sc(jsArr('two-pointer swap')),
[{input:'0 1 0 3 12',expectedOutput:'1 3 12 0 0'},{input:'0',expectedOutput:'0'}],
[{input:'1 0 0 0 1',expectedOutput:'1 1 0 0 0',isHidden:true},{input:'0 0 1',expectedOutput:'1 0 0',isHidden:true}]),

p(5,'Missing Number','Easy','Arrays',['Array','Math','Bit Manipulation'],
`Given an array \`nums\` containing \`n\` distinct numbers in the range \`[0, n]\`, return the only missing number.`,
'Space-separated integers.','The missing number.',
'1 ≤ n ≤ 10^4',
[{input:'3 0 1',output:'2'},{input:'0 1',output:'2'}],
sc(jsArr('XOR or sum formula')),
[{input:'3 0 1',expectedOutput:'2'},{input:'0 1',expectedOutput:'2'}],
[{input:'9 6 4 2 3 5 7 0 1',expectedOutput:'8',isHidden:true},{input:'0',expectedOutput:'1',isHidden:true}]),

p(6,'Best Time to Buy and Sell Stock','Easy','Arrays',['Array','Dynamic Programming'],
`Given an array \`prices\` where \`prices[i]\` is the price on day \`i\`, find the maximum profit you can achieve from one transaction. Return 0 if no profit is possible.`,
'Space-separated integers.','Maximum profit.',
'1 ≤ prices.length ≤ 10^5, 0 ≤ prices[i] ≤ 10^4',
[{input:'7 1 5 3 6 4',output:'5',explanation:'Buy day2 sell day5'},{input:'7 6 4 3 1',output:'0'}],
sc(jsArr('track min so far')),
[{input:'7 1 5 3 6 4',expectedOutput:'5'},{input:'7 6 4 3 1',expectedOutput:'0'}],
[{input:'1 2',expectedOutput:'1',isHidden:true},{input:'2 4 1',expectedOutput:'2',isHidden:true}]),

p(7,'Merge Sorted Array','Easy','Arrays',['Array','Two Pointers','Sorting'],
`Merge \`nums2\` into \`nums1\` in-place in sorted order. \`nums1\` has extra space at the end.\nInput: \`nums1\` length m+n (last n are zeros), \`nums2\` length n.`,
'First line: nums1 (m+n elements). Second line: m. Third line: nums2. Fourth line: n.',
'Space-separated merged sorted array.',
'0 ≤ m, n ≤ 200',
[{input:'1 2 3 0 0 0\n3\n2 5 6\n3',output:'1 2 2 3 5 6'},{input:'1\n1\n\n0',output:'1'}],
sc('function solution(nums1, m, nums2, n) {\n    // merge from end\n    \n}'),
[{input:'1 2 3 0 0 0\n3\n2 5 6\n3',expectedOutput:'1 2 2 3 5 6'},{input:'1\n1\n\n0',expectedOutput:'1'}],
[{input:'0\n0\n1\n1',expectedOutput:'1',isHidden:true}]),

p(8,'Single Number','Easy','Arrays',['Array','Bit Manipulation'],
`Every element in \`nums\` appears twice except one. Find the element that appears only once. Use O(1) space.`,
'Space-separated integers.','The single number.',
'1 ≤ nums.length ≤ 3×10^4, nums.length is odd',
[{input:'2 2 1',output:'1'},{input:'4 1 2 1 2',output:'4'}],
sc(jsArr('XOR all elements')),
[{input:'2 2 1',expectedOutput:'1'},{input:'4 1 2 1 2',expectedOutput:'4'}],
[{input:'1',expectedOutput:'1',isHidden:true},{input:'3 5 3',expectedOutput:'5',isHidden:true}]),

p(9,'Rotate Array','Easy','Arrays',['Array','Two Pointers','Math'],
`Rotate array \`nums\` to the right by \`k\` steps in-place.`,
'First line: space-separated integers. Second line: k.',
'Space-separated rotated array.',
'1 ≤ nums.length ≤ 10^5, 0 ≤ k ≤ 10^5',
[{input:'1 2 3 4 5 6 7\n3',output:'5 6 7 1 2 3 4'},{input:'-1 -100 3 99\n2',output:'3 99 -1 -100'}],
sc('function solution(nums, k) {\n    // reverse trick\n    \n}'),
[{input:'1 2 3 4 5 6 7\n3',expectedOutput:'5 6 7 1 2 3 4'},{input:'-1 -100 3 99\n2',expectedOutput:'3 99 -1 -100'}],
[{input:'1 2\n3',expectedOutput:'2 1',isHidden:true}]),

p(10,'Majority Element','Easy','Arrays',['Array','Boyer-Moore Voting'],
`Given an array of size \`n\`, return the majority element — the element that appears more than \`n/2\` times. It always exists.`,
'Space-separated integers.','The majority element.',
'1 ≤ n ≤ 5×10^4',
[{input:'3 2 3',output:'3'},{input:'2 2 1 1 1 2 2',output:'2'}],
sc(jsArr('Boyer-Moore voting')),
[{input:'3 2 3',expectedOutput:'3'},{input:'2 2 1 1 1 2 2',expectedOutput:'2'}],
[{input:'6 5 5',expectedOutput:'5',isHidden:true},{input:'1',expectedOutput:'1',isHidden:true}]),

/* ═══════════════════ STRINGS 11-20 ═══════════════════ */
p(11,'Reverse String','Easy','Strings',['String','Two Pointers'],
`Reverse a string represented as an array of characters in-place.`,
'A string of characters.',
'Reversed string.',
'1 ≤ s.length ≤ 10^5',
[{input:'hello',output:'olleh'},{input:'Hannah',output:'hannaH'}],
sc(jsStr('two-pointer swap')),
[{input:'hello',expectedOutput:'olleh'},{input:'Hannah',expectedOutput:'hannaH'}],
[{input:'a',expectedOutput:'a',isHidden:true},{input:'abcde',expectedOutput:'edcba',isHidden:true}]),

p(12,'Valid Palindrome','Easy','Strings',['String','Two Pointers'],
`A string is a palindrome if, after converting to lowercase and removing non-alphanumeric characters, it reads the same forwards and backwards. Return true/false.`,
'A string.','true or false.',
'1 ≤ s.length ≤ 2×10^5',
[{input:'A man, a plan, a canal: Panama',output:'true'},{input:'race a car',output:'false'}],
sc(jsStr('filter then two-pointer')),
[{input:'A man, a plan, a canal: Panama',expectedOutput:'true'},{input:'race a car',expectedOutput:'false'}],
[{input:' ',expectedOutput:'true',isHidden:true},{input:'0P',expectedOutput:'false',isHidden:true}]),

p(13,'Valid Anagram','Easy','Strings',['String','Sorting','Hash Table'],
`Given two strings \`s\` and \`t\`, return true if \`t\` is an anagram of \`s\`.`,
'Two strings on separate lines.','true or false.',
'1 ≤ s.length, t.length ≤ 5×10^4, lowercase English letters',
[{input:'anagram\nnagaram',output:'true'},{input:'rat\ncar',output:'false'}],
sc(jsTwoStr('character frequency map')),
[{input:'anagram\nnagaram',expectedOutput:'true'},{input:'rat\ncar',expectedOutput:'false'}],
[{input:'a\na',expectedOutput:'true',isHidden:true},{input:'ab\nba',expectedOutput:'true',isHidden:true}]),

p(14,'Longest Common Prefix','Easy','Strings',['String'],
`Find the longest common prefix string among an array of strings. Return "" if there is none.`,
'Space-separated strings.','The longest common prefix or empty string.',
'1 ≤ strs.length ≤ 200, 0 ≤ strs[i].length ≤ 200, lowercase English only',
[{input:'flower flow flight',output:'fl'},{input:'dog racecar car',output:''}],
sc(jsArr('horizontal scanning or vertical')),
[{input:'flower flow flight',expectedOutput:'fl'},{input:'dog racecar car',expectedOutput:''}],
[{input:'interview inter',expectedOutput:'inter',isHidden:true},{input:'a',expectedOutput:'a',isHidden:true}]),

p(15,'Valid Parentheses','Easy','Stack',['String','Stack'],
`Given a string containing only \`()\`, \`[]\`, \`{}\`, determine if the input is valid: brackets must be closed in the correct order.`,
'A string.','true or false.',
'1 ≤ s.length ≤ 10^4',
[{input:'()',output:'true'},{input:'()[]{} ',output:'true'},{input:'(]',output:'false'}],
sc(jsStr('use a stack')),
[{input:'()',expectedOutput:'true'},{input:'(]',expectedOutput:'false'}],
[{input:'([)]',expectedOutput:'false',isHidden:true},{input:'{[]}',expectedOutput:'true',isHidden:true}]),

p(16,'Count Vowels','Easy','Strings',['String'],
`Count the number of vowels (a,e,i,o,u — both cases) in a string.`,
'A string.','Number of vowels.',
'0 ≤ s.length ≤ 10^5',
[{input:'Hello World',output:'3'},{input:'aeiouAEIOU',output:'10'}],
sc(jsStr('iterate and check')),
[{input:'Hello World',expectedOutput:'3'},{input:'aeiouAEIOU',expectedOutput:'10'}],
[{input:'rhythm',expectedOutput:'0',isHidden:true},{input:'',expectedOutput:'0',isHidden:true}]),

p(17,'First Non-Repeating Character','Easy','Strings',['String','Hash Table','Queue'],
`Given a string \`s\`, find the index of the first non-repeating character. If none exists return -1.`,
'A string.','Index of first non-repeating character or -1.',
'1 ≤ s.length ≤ 10^5, lowercase English only',
[{input:'leetcode',output:'0'},{input:'aabb',output:'-1'}],
sc(jsStr('frequency map then scan')),
[{input:'leetcode',expectedOutput:'0'},{input:'aabb',expectedOutput:'-1'}],
[{input:'loveleetcode',expectedOutput:'2',isHidden:true},{input:'aadadaad',expectedOutput:'-1',isHidden:true}]),

p(18,'Reverse Words in String','Easy','Strings',['String','Two Pointers'],
`Given a string, reverse the order of words (words separated by spaces). Remove extra spaces.`,
'A string.','Words in reversed order, single space separated.',
'1 ≤ s.length ≤ 10^4',
[{input:'the sky is blue',output:'blue is sky the'},{input:'  hello world  ',output:'world hello'}],
sc(jsStr('split, reverse, join')),
[{input:'the sky is blue',expectedOutput:'blue is sky the'},{input:'  hello world  ',expectedOutput:'world hello'}],
[{input:'a good   example',expectedOutput:'example good a',isHidden:true}]),

p(19,'Check Subsequence','Easy','Strings',['String','Two Pointers','Dynamic Programming'],
`Return true if string \`s\` is a subsequence of string \`t\`.`,
'Two strings on separate lines (s then t).','true or false.',
'0 ≤ s.length ≤ 100, 0 ≤ t.length ≤ 10^4, lowercase English',
[{input:'ace\nabcde',output:'true'},{input:'axc\nahbgdc',output:'false'}],
sc(jsTwoStr('two-pointer on both strings')),
[{input:'ace\nabcde',expectedOutput:'true'},{input:'axc\nahbgdc',expectedOutput:'false'}],
[{input:'\nahbgdc',expectedOutput:'true',isHidden:true},{input:'aaaaaa\nbbaaaa',expectedOutput:'false',isHidden:true}]),

p(20,'Longest Palindromic Substring','Medium','Strings',['String','Dynamic Programming','Two Pointers'],
`Given a string \`s\`, return the longest palindromic substring.`,
'A string.','The longest palindromic substring (any if tie).',
'1 ≤ s.length ≤ 1000, lowercase English',
[{input:'babad',output:'bab'},{input:'cbbd',output:'bb'}],
sc(jsStr('expand around center')),
[{input:'babad',expectedOutput:'bab'},{input:'cbbd',expectedOutput:'bb'}],
[{input:'a',expectedOutput:'a',isHidden:true},{input:'racecar',expectedOutput:'racecar',isHidden:true}]),

/* ═══════════════════ TWO POINTERS / SLIDING WINDOW 21-30 ═══════════════════ */
p(21,'Remove Duplicates from Sorted Array','Easy','Two Pointers',['Array','Two Pointers'],
`Given a sorted array \`nums\`, remove duplicates in-place and return the new length k. The first k elements must be unique.`,
'Space-separated sorted integers.','Number k of unique elements.',
'1 ≤ nums.length ≤ 3×10^4, sorted non-decreasing',
[{input:'1 1 2',output:'2'},{input:'0 0 1 1 1 2 2 3 3 4',output:'5'}],
sc(jsArr('slow/fast pointer')),
[{input:'1 1 2',expectedOutput:'2'},{input:'0 0 1 1 1 2 2 3 3 4',expectedOutput:'5'}],
[{input:'1',expectedOutput:'1',isHidden:true},{input:'1 1',expectedOutput:'1',isHidden:true}]),

p(22,'Container With Most Water','Medium','Two Pointers',['Array','Two Pointers','Greedy'],
`Given \`n\` non-negative integers as heights of lines, find two lines that together with the x-axis form a container that holds the most water.`,
'Space-separated integers.','Maximum area.',
'2 ≤ n ≤ 10^5, 0 ≤ height[i] ≤ 10^4',
[{input:'1 8 6 2 5 4 8 3 7',output:'49'},{input:'1 1',output:'1'}],
sc(jsArr('two pointer from edges')),
[{input:'1 8 6 2 5 4 8 3 7',expectedOutput:'49'},{input:'1 1',expectedOutput:'1'}],
[{input:'4 3 2 1 4',expectedOutput:'16',isHidden:true},{input:'1 2 1',expectedOutput:'2',isHidden:true}]),

p(23,'Longest Substring Without Repeating Characters','Medium','Sliding Window',['String','Sliding Window','Hash Table'],
`Find the length of the longest substring without repeating characters.`,
'A string.','Length of longest substring.',
'0 ≤ s.length ≤ 5×10^4',
[{input:'abcabcbb',output:'3'},{input:'bbbbb',output:'1'},{input:'pwwkew',output:'3'}],
sc(jsStr('sliding window with set')),
[{input:'abcabcbb',expectedOutput:'3'},{input:'bbbbb',expectedOutput:'1'}],
[{input:'pwwkew',expectedOutput:'3',isHidden:true},{input:'',expectedOutput:'0',isHidden:true}]),

p(24,'Minimum Size Subarray Sum','Medium','Sliding Window',['Array','Sliding Window','Binary Search'],
`Given an array \`nums\` and integer \`target\`, return the minimal length of a subarray whose sum ≥ target. Return 0 if impossible.`,
'First line: target. Second line: space-separated nums.','Minimal length or 0.',
'1 ≤ target ≤ 10^9, 1 ≤ nums.length ≤ 10^5',
[{input:'7\n2 3 1 2 4 3',output:'2'},{input:'4\n1 4 4',output:'1'}],
sc(jsTwoArr('sliding window expand/shrink')),
[{input:'7\n2 3 1 2 4 3',expectedOutput:'2'},{input:'4\n1 4 4',expectedOutput:'1'}],
[{input:'11\n1 1 1 1 1 1 1 1',expectedOutput:'0',isHidden:true},{input:'15\n1 2 3 4 5',expectedOutput:'5',isHidden:true}]),

p(25,'Subarray Sum Equals K','Medium','Hashing',['Array','Hash Table','Prefix Sum'],
`Given an integer array \`nums\` and integer \`k\`, return the total number of subarrays whose sum equals \`k\`.`,
'First line: space-separated nums. Second line: k.','Count of subarrays.',
'1 ≤ nums.length ≤ 2×10^4, -1000 ≤ nums[i] ≤ 1000',
[{input:'1 1 1\n2',output:'2'},{input:'1 2 3\n3',output:'2'}],
sc(jsTwoArr('prefix sum + hash map')),
[{input:'1 1 1\n2',expectedOutput:'2'},{input:'1 2 3\n3',expectedOutput:'2'}],
[{input:'-1 -1 1\n0',expectedOutput:'1',isHidden:true}]),

p(26,'Product of Array Except Self','Medium','Arrays',['Array','Prefix Sum'],
`Given an integer array \`nums\`, return an array \`output\` where \`output[i]\` is the product of all elements except \`nums[i]\`. No division allowed, O(n).`,
'Space-separated integers.','Space-separated output array.',
'2 ≤ nums.length ≤ 10^5, -30 ≤ nums[i] ≤ 30',
[{input:'1 2 3 4',output:'24 12 8 6'},{input:'-1 1 0 -3 3',output:'0 0 9 0 0'}],
sc(jsArr('left and right pass')),
[{input:'1 2 3 4',expectedOutput:'24 12 8 6'},{input:'-1 1 0 -3 3',expectedOutput:'0 0 9 0 0'}],
[{input:'2 3',expectedOutput:'3 2',isHidden:true}]),

p(27,'Sliding Window Maximum','Hard','Sliding Window',['Array','Sliding Window','Queue','Monotonic Queue'],
`Given an array \`nums\` and window size \`k\`, return the max of each sliding window.`,
'First line: space-separated nums. Second line: k.','Space-separated maximums.',
'1 ≤ nums.length ≤ 10^5, 1 ≤ k ≤ nums.length',
[{input:'1 3 -1 -3 5 3 6 7\n3',output:'3 3 5 5 6 7'},{input:'1\n1',output:'1'}],
sc('function solution(nums, k) {\n    // deque\n    \n}'),
[{input:'1 3 -1 -3 5 3 6 7\n3',expectedOutput:'3 3 5 5 6 7'},{input:'1\n1',expectedOutput:'1'}],
[{input:'9 11\n2',expectedOutput:'11',isHidden:true}]),

p(28,'3Sum','Medium','Two Pointers',['Array','Two Pointers','Sorting'],
`Find all unique triplets in \`nums\` such that they sum to zero. No duplicate triplets.`,
'Space-separated integers.','Each triplet on a new line, space-separated, sorted.',
'-10^5 ≤ nums[i] ≤ 10^5',
[{input:'-1 0 1 2 -1 -4',output:'-1 -1 2\n-1 0 1'},{input:'0 1 1',output:''}],
sc(jsArr('sort + two pointers')),
[{input:'-1 0 1 2 -1 -4',expectedOutput:'-1 -1 2\n-1 0 1'},{input:'0 1 1',expectedOutput:''}],
[{input:'0 0 0',expectedOutput:'0 0 0',isHidden:true}]),

p(29,'Longest Consecutive Sequence','Medium','Hashing',['Array','Hash Table','Union Find'],
`Given an unsorted array, find the length of the longest consecutive elements sequence. O(n) time.`,
'Space-separated integers.','Length of longest consecutive sequence.',
'0 ≤ nums.length ≤ 10^5',
[{input:'100 4 200 1 3 2',output:'4'},{input:'0 3 7 2 5 8 4 6 0 1',output:'9'}],
sc(jsArr('hash set, start detection')),
[{input:'100 4 200 1 3 2',expectedOutput:'4'},{input:'0 3 7 2 5 8 4 6 0 1',expectedOutput:'9'}],
[{input:'',expectedOutput:'0',isHidden:true}]),

p(30,'Trapping Rain Water','Hard','Two Pointers',['Array','Two Pointers','Dynamic Programming','Stack'],
`Given an array of heights, compute how much water it can trap after raining.`,
'Space-separated non-negative integers.','Total water trapped.',
'1 ≤ height.length ≤ 2×10^4',
[{input:'0 1 0 2 1 0 1 3 2 1 2 1',output:'6'},{input:'4 2 0 3 2 5',output:'9'}],
sc(jsArr('two pointer maxL maxR')),
[{input:'0 1 0 2 1 0 1 3 2 1 2 1',expectedOutput:'6'},{input:'4 2 0 3 2 5',expectedOutput:'9'}],
[{input:'3 0 2 0 4',expectedOutput:'7',isHidden:true}]),

/* ═══════════════════ BINARY SEARCH 31-38 ═══════════════════ */
p(31,'Binary Search','Easy','Binary Search',['Array','Binary Search'],
`Given a sorted array \`nums\` and a \`target\`, return the index of target using binary search. Return -1 if not found.`,
'First line: sorted space-separated integers. Second line: target.','Index or -1.',
'1 ≤ nums.length ≤ 10^4, sorted ascending, all distinct',
[{input:'-1 0 3 5 9 12\n9',output:'4'},{input:'-1 0 3 5 9 12\n2',output:'-1'}],
sc(jsTwoArr('classic binary search')),
[{input:'-1 0 3 5 9 12\n9',expectedOutput:'4'},{input:'-1 0 3 5 9 12\n2',expectedOutput:'-1'}],
[{input:'5\n5',expectedOutput:'0',isHidden:true},{input:'1 2 3\n3',expectedOutput:'2',isHidden:true}]),

p(32,'Search Insert Position','Easy','Binary Search',['Array','Binary Search'],
`Given a sorted array and a target, return the index if found, or the index where it would be inserted to maintain order.`,
'First line: sorted space-separated integers. Second line: target.','Index.',
'1 ≤ nums.length ≤ 10^4',
[{input:'1 3 5 6\n5',output:'2'},{input:'1 3 5 6\n2',output:'1'}],
sc(jsTwoArr('binary search variant')),
[{input:'1 3 5 6\n5',expectedOutput:'2'},{input:'1 3 5 6\n2',expectedOutput:'1'}],
[{input:'1 3 5 6\n7',expectedOutput:'4',isHidden:true},{input:'1 3 5 6\n0',expectedOutput:'0',isHidden:true}]),

p(33,'Find Minimum in Rotated Sorted Array','Medium','Binary Search',['Array','Binary Search'],
`Find the minimum element in a rotated sorted array with no duplicates.`,
'Space-separated integers.','Minimum element.',
'1 ≤ nums.length ≤ 5000, all unique',
[{input:'3 4 5 1 2',output:'1'},{input:'4 5 6 7 0 1 2',output:'0'}],
sc(jsArr('binary search on rotation')),
[{input:'3 4 5 1 2',expectedOutput:'1'},{input:'4 5 6 7 0 1 2',expectedOutput:'0'}],
[{input:'11 13 15 17',expectedOutput:'11',isHidden:true}]),

p(34,'Search in Rotated Sorted Array','Medium','Binary Search',['Array','Binary Search'],
`Search for \`target\` in a rotated sorted array. Return index or -1.`,
'First line: rotated sorted array. Second line: target.','Index or -1.',
'1 ≤ nums.length ≤ 5000, all unique',
[{input:'4 5 6 7 0 1 2\n0',output:'4'},{input:'4 5 6 7 0 1 2\n3',output:'-1'}],
sc(jsTwoArr('modified binary search')),
[{input:'4 5 6 7 0 1 2\n0',expectedOutput:'4'},{input:'4 5 6 7 0 1 2\n3',expectedOutput:'-1'}],
[{input:'1\n0',expectedOutput:'-1',isHidden:true},{input:'3 1\n1',expectedOutput:'1',isHidden:true}]),

p(35,'Kth Smallest in Matrix','Medium','Binary Search',['Matrix','Binary Search','Heap'],
`Given an n×n sorted matrix (each row/col sorted ascending), find the kth smallest element.`,
'First line: n. Next n lines: space-separated row values. Last line: k.','The kth smallest element.',
'1 ≤ n ≤ 300',
[{input:'3\n1 5 9\n10 11 13\n12 13 15\n8',output:'13'},{input:'2\n1 2\n1 3\n2',output:'1'}],
sc('function solution(matrix, k) {\n    // binary search on value\n    \n}'),
[{input:'3\n1 5 9\n10 11 13\n12 13 15\n8',expectedOutput:'13'},{input:'2\n1 2\n1 3\n2',expectedOutput:'1'}],
[{input:'1\n1\n1',expectedOutput:'1',isHidden:true}]),

p(36,'Peak Element','Medium','Binary Search',['Array','Binary Search'],
`A peak element is greater than its neighbors. Find any peak element's index. Assume nums[-1]=nums[n]=-∞.`,
'Space-separated integers.','Index of a peak element.',
'1 ≤ nums.length ≤ 1000, nums[i] ≠ nums[i+1]',
[{input:'1 2 3 1',output:'2'},{input:'1 2 1 3 5 6 4',output:'5'}],
sc(jsArr('binary search on slope')),
[{input:'1 2 3 1',expectedOutput:'2'},{input:'1 2 1 3 5 6 4',expectedOutput:'5'}],
[{input:'1',expectedOutput:'0',isHidden:true}]),

p(37,'Count Negatives in Sorted Matrix','Easy','Binary Search',['Array','Binary Search','Matrix'],
`Given a sorted matrix (row and col sorted descending), count negative numbers.`,
'First line: rows r and cols c. Next r lines: space-separated values.','Count of negatives.',
'1 ≤ r,c ≤ 100, -100 ≤ grid[i][j] ≤ 100',
[{input:'4 4\n4 3 2 -1\n3 2 1 -1\n1 1 -1 -2\n-1 -1 -2 -3',output:'8'},{input:'3 3\n3 2 1\n1 1 0\n0 0 0',output:'0'}],
sc('function solution(grid) {\n    // staircase walk\n    \n}'),
[{input:'4 4\n4 3 2 -1\n3 2 1 -1\n1 1 -1 -2\n-1 -1 -2 -3',expectedOutput:'8'},{input:'3 3\n3 2 1\n1 1 0\n0 0 0',expectedOutput:'0'}],
[{input:'1 1\n-5',expectedOutput:'1',isHidden:true}]),

p(38,'Median of Two Sorted Arrays','Hard','Binary Search',['Array','Binary Search','Divide and Conquer'],
`Find the median of two sorted arrays in O(log(m+n)) time.`,
'First line: array1. Second line: array2.','Median (float, 1 decimal place).',
'0 ≤ m,n ≤ 1000',
[{input:'1 3\n2',output:'2.0'},{input:'1 2\n3 4',output:'2.5'}],
sc('function solution(nums1, nums2) {\n    // binary search on partition\n    \n}'),
[{input:'1 3\n2',expectedOutput:'2.0'},{input:'1 2\n3 4',expectedOutput:'2.5'}],
[{input:'0 0\n0 0',expectedOutput:'0.0',isHidden:true}]),

/* ═══════════════════ LINKED LIST 39-46 ═══════════════════ */
p(39,'Reverse Linked List','Easy','Linked List',['Linked List','Recursion'],
`Reverse a singly linked list. Input: space-separated values representing the list.`,
'Space-separated integers (list nodes).','Space-separated reversed list.',
'0 ≤ n ≤ 5000, -5000 ≤ val ≤ 5000',
[{input:'1 2 3 4 5',output:'5 4 3 2 1'},{input:'1 2',output:'2 1'},{input:'',output:''}],
sc(jsArr('iterative or recursive reversal')),
[{input:'1 2 3 4 5',expectedOutput:'5 4 3 2 1'},{input:'1 2',expectedOutput:'2 1'}],
[{input:'1',expectedOutput:'1',isHidden:true}]),

p(40,'Detect Cycle in Linked List','Easy','Linked List',['Linked List','Floyd\'s Algorithm'],
`Given a linked list, return true if it has a cycle. For this problem, a sorted input means no cycle; an unsorted means cycle detection by duplicate values.`,
'Space-separated integers (with possible duplicates indicating cycle).','true or false.',
'0 ≤ n ≤ 10^4',
[{input:'3 2 0 4 2',output:'true'},{input:'1 2',output:'false'}],
sc(jsArr('Floyd\'s slow/fast pointer')),
[{input:'3 2 0 4 2',expectedOutput:'true'},{input:'1 2',expectedOutput:'false'}],
[{input:'1',expectedOutput:'false',isHidden:true},{input:'1 1',expectedOutput:'true',isHidden:true}]),

p(41,'Merge Two Sorted Lists','Easy','Linked List',['Linked List','Recursion'],
`Merge two sorted linked lists and return the merged sorted list.`,
'Two lines, each with space-separated sorted integers.','Single sorted space-separated list.',
'0 ≤ list length ≤ 50, -100 ≤ val ≤ 100',
[{input:'1 2 4\n1 3 4',output:'1 1 2 3 4 4'},{input:'\n',output:''},{input:'\n0',output:'0'}],
sc('function solution(list1, list2) {\n    // merge two sorted arrays\n    \n}'),
[{input:'1 2 4\n1 3 4',expectedOutput:'1 1 2 3 4 4'},{input:'\n0',expectedOutput:'0'}],
[{input:'5\n1 2 4',expectedOutput:'1 2 4 5',isHidden:true}]),

p(42,'Middle of Linked List','Easy','Linked List',['Linked List','Two Pointers'],
`Return the middle node of a linked list. If two middles, return the second.`,
'Space-separated integers.','Space-separated list from middle to end.',
'1 ≤ n ≤ 100',
[{input:'1 2 3 4 5',output:'3 4 5'},{input:'1 2 3 4 5 6',output:'4 5 6'}],
sc(jsArr('slow/fast pointer')),
[{input:'1 2 3 4 5',expectedOutput:'3 4 5'},{input:'1 2 3 4 5 6',expectedOutput:'4 5 6'}],
[{input:'1',expectedOutput:'1',isHidden:true}]),

p(43,'Remove Nth Node from End','Medium','Linked List',['Linked List','Two Pointers'],
`Remove the nth node from the end of the list.`,
'First line: space-separated integers. Second line: n.','Resulting list.',
'1 ≤ sz ≤ 30, 1 ≤ n ≤ sz',
[{input:'1 2 3 4 5\n2',output:'1 2 3 5'},{input:'1\n1',output:''},{input:'1 2\n1',output:'1'}],
sc('function solution(head, n) {\n    // two-pointer gap of n\n    \n}'),
[{input:'1 2 3 4 5\n2',expectedOutput:'1 2 3 5'},{input:'1\n1',expectedOutput:''}],
[{input:'1 2\n2',expectedOutput:'2',isHidden:true}]),

p(44,'Palindrome Linked List','Easy','Linked List',['Linked List','Two Pointers','Recursion'],
`Return true if the linked list is a palindrome.`,
'Space-separated integers.','true or false.',
'1 ≤ n ≤ 10^5',
[{input:'1 2 2 1',output:'true'},{input:'1 2',output:'false'}],
sc(jsArr('find middle, reverse second half')),
[{input:'1 2 2 1',expectedOutput:'true'},{input:'1 2',expectedOutput:'false'}],
[{input:'1',expectedOutput:'true',isHidden:true},{input:'1 2 3 2 1',expectedOutput:'true',isHidden:true}]),

p(45,'Intersection of Two Linked Lists','Easy','Linked List',['Linked List','Hash Table','Two Pointers'],
`Given two lists that may share a common suffix, return the length of the shared part. (Simplified: return overlap length.)`,
'Two lines of space-separated integers.','Length of common suffix.',
'0 ≤ list length ≤ 3×10^4',
[{input:'4 1 8 4 5\n5 6 1 8 4 5',output:'3'},{input:'1 9 1 2 4\n3 2 4',output:'2'}],
sc('function solution(listA, listB) {\n    // two-pointer trick\n    \n}'),
[{input:'4 1 8 4 5\n5 6 1 8 4 5',expectedOutput:'3'},{input:'1 9 1 2 4\n3 2 4',expectedOutput:'2'}],
[{input:'2 6 4\n1 5',expectedOutput:'0',isHidden:true}]),

p(46,'Flatten Multilevel Doubly Linked List','Medium','Linked List',['Linked List','DFS','Stack'],
`Flatten a multilevel list (represented as a sequence with ">" indicating a child) to a single-level list.`,
'Space-separated integers, ">" indicates child start, "<" end.','Flattened sequence.',
'1 ≤ n ≤ 1000',
[{input:'1 2 > 3 4 < 5',output:'1 2 3 4 5'}],
sc(jsArr('stack-based DFS')),
[{input:'1 2 > 3 4 < 5',expectedOutput:'1 2 3 4 5'}],
[{input:'1 > 2 < 3',expectedOutput:'1 2 3',isHidden:true}]),

/* ═══════════════════ TREES 47-56 ═══════════════════ */
p(47,'Maximum Depth of Binary Tree','Easy','Trees',['Tree','DFS','BFS','Recursion'],
`Given the root of a binary tree (level-order, -1 = null), return its maximum depth.`,
'Space-separated level-order integers (-1 = null).','Maximum depth.',
'0 ≤ n ≤ 10^4',
[{input:'3 9 20 -1 -1 15 7',output:'3'},{input:'1 -1 2',output:'2'}],
sc(jsArr('recursive DFS')),
[{input:'3 9 20 -1 -1 15 7',expectedOutput:'3'},{input:'1 -1 2',expectedOutput:'2'}],
[{input:'',expectedOutput:'0',isHidden:true},{input:'1',expectedOutput:'1',isHidden:true}]),

p(48,'Invert Binary Tree','Easy','Trees',['Tree','DFS','BFS','Recursion'],
`Invert a binary tree (mirror it). Return level-order output.`,
'Space-separated level-order integers (-1 = null).','Level-order of inverted tree.',
'0 ≤ n ≤ 100',
[{input:'4 2 7 1 3 6 9',output:'4 7 2 9 6 3 1'},{input:'2 1 3',output:'2 3 1'}],
sc(jsArr('recursive swap children')),
[{input:'4 2 7 1 3 6 9',expectedOutput:'4 7 2 9 6 3 1'},{input:'2 1 3',expectedOutput:'2 3 1'}],
[{input:'',expectedOutput:'',isHidden:true}]),

p(49,'Symmetric Tree','Easy','Trees',['Tree','DFS','BFS','Recursion'],
`Check if a binary tree is a mirror of itself (symmetric around its center).`,
'Space-separated level-order integers (-1 = null).','true or false.',
'1 ≤ n ≤ 1000',
[{input:'1 2 2 3 4 4 3',output:'true'},{input:'1 2 2 -1 3 -1 3',output:'false'}],
sc(jsArr('recursive isMirror check')),
[{input:'1 2 2 3 4 4 3',expectedOutput:'true'},{input:'1 2 2 -1 3 -1 3',expectedOutput:'false'}],
[{input:'1',expectedOutput:'true',isHidden:true}]),

p(50,'Binary Tree Level Order Traversal','Medium','Trees',['Tree','BFS','Queue'],
`Return level-order traversal as levels separated by "|".`,
'Space-separated level-order integers (-1 = null).','Values per level separated by "|".',
'0 ≤ n ≤ 2000',
[{input:'3 9 20 -1 -1 15 7',output:'3|9 20|15 7'},{input:'1',output:'1'}],
sc(jsArr('BFS with queue')),
[{input:'3 9 20 -1 -1 15 7',expectedOutput:'3|9 20|15 7'},{input:'1',expectedOutput:'1'}],
[{input:'',expectedOutput:'',isHidden:true}]),

p(51,'Path Sum','Easy','Trees',['Tree','DFS','BFS'],
`Return true if the tree has a root-to-leaf path that sums to \`targetSum\`.`,
'First line: level-order tree (-1=null). Second line: targetSum.','true or false.',
'0 ≤ n ≤ 5000',
[{input:'5 4 8 11 -1 13 4 7 2 -1 -1 -1 1\n22',output:'true'},{input:'1 2 3\n5',output:'false'}],
sc(jsTwoArr('recursive DFS with remaining sum')),
[{input:'5 4 8 11 -1 13 4 7 2 -1 -1 -1 1\n22',expectedOutput:'true'},{input:'1 2 3\n5',expectedOutput:'false'}],
[{input:'\n0',expectedOutput:'false',isHidden:true}]),

p(52,'Lowest Common Ancestor of BST','Easy','Binary Search Tree',['Tree','BST','Recursion'],
`Given a BST and two values p and q, find their lowest common ancestor.`,
'First line: level-order BST (-1=null). Second line: p. Third line: q.','LCA value.',
'2 ≤ n ≤ 10^5, all values unique',
[{input:'6 2 8 0 4 7 9 -1 -1 3 5\n2\n8',output:'6'},{input:'6 2 8 0 4 7 9 -1 -1 3 5\n2\n4',output:'2'}],
sc('function solution(root, p, q) {\n    // navigate left/right in BST\n    \n}'),
[{input:'6 2 8 0 4 7 9 -1 -1 3 5\n2\n8',expectedOutput:'6'},{input:'6 2 8 0 4 7 9 -1 -1 3 5\n2\n4',expectedOutput:'2'}],
[{input:'2 1\n2\n1',expectedOutput:'2',isHidden:true}]),

p(53,'Validate Binary Search Tree','Medium','Binary Search Tree',['Tree','BST','DFS','Recursion'],
`Determine if a binary tree is a valid BST.`,
'Space-separated level-order integers (-1 = null).','true or false.',
'1 ≤ n ≤ 10^4',
[{input:'2 1 3',output:'true'},{input:'5 1 4 -1 -1 3 6',output:'false'}],
sc(jsArr('in-order traversal check')),
[{input:'2 1 3',expectedOutput:'true'},{input:'5 1 4 -1 -1 3 6',expectedOutput:'false'}],
[{input:'2 2 2',expectedOutput:'false',isHidden:true}]),

p(54,'Binary Tree Zigzag Level Order','Medium','Trees',['Tree','BFS','Queue'],
`Return the zigzag level-order traversal (alternate left-to-right and right-to-left).`,
'Space-separated level-order integers (-1 = null).','Values per level separated by "|", alternating direction.',
'0 ≤ n ≤ 2000',
[{input:'3 9 20 -1 -1 15 7',output:'3|20 9|15 7'},{input:'1',output:'1'}],
sc(jsArr('BFS + reverse alternate levels')),
[{input:'3 9 20 -1 -1 15 7',expectedOutput:'3|20 9|15 7'},{input:'1',expectedOutput:'1'}],
[{input:'1 2 3',expectedOutput:'1|3 2',isHidden:true}]),

p(55,'Diameter of Binary Tree','Easy','Trees',['Tree','DFS'],
`Given a binary tree, return the length of its diameter (longest path between any two nodes).`,
'Space-separated level-order integers (-1 = null).','Diameter length.',
'1 ≤ n ≤ 10^4',
[{input:'1 2 3 4 5',output:'3'},{input:'1 2',output:'1'}],
sc(jsArr('dfs returning height, update global max')),
[{input:'1 2 3 4 5',expectedOutput:'3'},{input:'1 2',expectedOutput:'1'}],
[{input:'1',expectedOutput:'0',isHidden:true}]),

p(56,'Serialize and Deserialize Binary Tree','Hard','Trees',['Tree','BFS','DFS','String'],
`Design an algorithm to serialize (tree → string) and deserialize (string → tree). Output the level-order of the deserialized tree.`,
'Space-separated level-order integers (-1 = null).','Level-order of re-built tree.',
'0 ≤ n ≤ 10^4',
[{input:'1 2 3 -1 -1 4 5',output:'1 2 3 -1 -1 4 5'},{input:'',output:''}],
sc(jsArr('BFS serialize/deserialize')),
[{input:'1 2 3 -1 -1 4 5',expectedOutput:'1 2 3 -1 -1 4 5'},{input:'',expectedOutput:''}],
[{input:'1 2',expectedOutput:'1 2',isHidden:true}]),

/* ═══════════════════ GRAPHS 57-64 ═══════════════════ */
p(57,'Number of Islands','Medium','Graphs',['Array','BFS','DFS','Union Find','Matrix'],
`Given a grid of 1s (land) and 0s (water), count the number of islands.`,
'First line: rows r and cols c. Next r lines: space-separated 0/1.','Number of islands.',
'1 ≤ r,c ≤ 300',
[{input:'4 5\n1 1 1 1 0\n1 1 0 1 0\n1 1 0 0 0\n0 0 0 0 0',output:'1'},{input:'4 5\n1 1 0 0 0\n1 1 0 0 0\n0 0 1 0 0\n0 0 0 1 1',output:'3'}],
sc('function solution(grid) {\n    // DFS flood fill\n    \n}'),
[{input:'4 5\n1 1 1 1 0\n1 1 0 1 0\n1 1 0 0 0\n0 0 0 0 0',expectedOutput:'1'},{input:'4 5\n1 1 0 0 0\n1 1 0 0 0\n0 0 1 0 0\n0 0 0 1 1',expectedOutput:'3'}],
[{input:'1 1\n1',expectedOutput:'1',isHidden:true},{input:'1 1\n0',expectedOutput:'0',isHidden:true}]),

p(58,'Clone Graph','Medium','Graphs',['BFS','DFS','Hash Table','Graph'],
`Clone a connected undirected graph. Represent as adjacency list. Return the node count after cloning.`,
'First line: n nodes. Next lines: "node: neighbor1 neighbor2".','Number of nodes in cloned graph.',
'0 ≤ n ≤ 100',
[{input:'4\n1: 2 4\n2: 1 3\n3: 2 4\n4: 1 3',output:'4'},{input:'1\n1:',output:'1'}],
sc('function solution(graph) {\n    // BFS + hash map\n    \n}'),
[{input:'4\n1: 2 4\n2: 1 3\n3: 2 4\n4: 1 3',expectedOutput:'4'}],
[{input:'1\n1:',expectedOutput:'1',isHidden:true}]),

p(59,'Course Schedule','Medium','Graphs',['BFS','DFS','Topological Sort','Graph'],
`Given \`numCourses\` and prerequisites as pairs, return true if all courses can be finished (no cycles).`,
'First line: numCourses. Next lines: "a b" meaning a depends on b.','true or false.',
'1 ≤ numCourses ≤ 2000',
[{input:'2\n1 0',output:'true'},{input:'2\n1 0\n0 1',output:'false'}],
sc('function solution(numCourses, prerequisites) {\n    // topological sort / cycle detection\n    \n}'),
[{input:'2\n1 0',expectedOutput:'true'},{input:'2\n1 0\n0 1',expectedOutput:'false'}],
[{input:'1',expectedOutput:'true',isHidden:true}]),

p(60,'Pacific Atlantic Water Flow','Medium','Graphs',['Array','BFS','DFS','Matrix'],
`Find cells from which water can flow to both the Pacific (top/left) and Atlantic (bottom/right) oceans.`,
'First line: r c. Next r lines: space-separated heights.','Sorted cell coordinates as "r c" per line.',
'1 ≤ r,c ≤ 200',
[{input:'5 5\n1 2 2 3 5\n3 2 3 4 4\n2 4 5 3 1\n6 7 1 4 5\n5 1 1 2 4',output:'0 4\n1 3\n1 4\n2 2\n3 0\n3 1\n4 0'}],
sc('function solution(heights) {\n    // reverse BFS from both oceans\n    \n}'),
[{input:'5 5\n1 2 2 3 5\n3 2 3 4 4\n2 4 5 3 1\n6 7 1 4 5\n5 1 1 2 4',expectedOutput:'0 4\n1 3\n1 4\n2 2\n3 0\n3 1\n4 0'}],
[{input:'1 1\n1',expectedOutput:'0 0',isHidden:true}]),

p(61,'Walls and Gates','Medium','Graphs',['BFS','Matrix'],
`Fill each empty room with distance to nearest gate. -1=wall, 0=gate, INF=empty room (use 2147483647).`,
'First line: r c. Next r lines: space-separated integers.','Filled grid.',
'1 ≤ r,c ≤ 250',
[{input:'4 4\n2147483647 -1 0 2147483647\n2147483647 2147483647 2147483647 -1\n2147483647 -1 2147483647 -1\n0 -1 2147483647 2147483647',output:'3 -1 0 1\n2 2 1 -1\n1 -1 2 -1\n0 -1 3 4'}],
sc('function solution(rooms) {\n    // multi-source BFS from gates\n    \n}'),
[{input:'4 4\n2147483647 -1 0 2147483647\n2147483647 2147483647 2147483647 -1\n2147483647 -1 2147483647 -1\n0 -1 2147483647 2147483647',expectedOutput:'3 -1 0 1\n2 2 1 -1\n1 -1 2 -1\n0 -1 3 4'}],
[{input:'1 2\n0 2147483647',expectedOutput:'0 1',isHidden:true}]),

p(62,'Word Ladder','Hard','Graphs',['BFS','Hash Table','String'],
`Find the length of shortest transformation from \`beginWord\` to \`endWord\` changing one letter at a time (each intermediate word must be in \`wordList\`). Return 0 if impossible.`,
'First line: beginWord. Second line: endWord. Third line: space-separated wordList.','Length or 0.',
'1 ≤ word.length ≤ 10, 1 ≤ wordList.length ≤ 5000',
[{input:'hit\ncog\nhot dot dog lot log cog',output:'5'},{input:'hit\ncog\nhot dot dog lot log',output:'0'}],
sc('function solution(beginWord, endWord, wordList) {\n    // BFS level by level\n    \n}'),
[{input:'hit\ncog\nhot dot dog lot log cog',expectedOutput:'5'},{input:'hit\ncog\nhot dot dog lot log',expectedOutput:'0'}],
[{input:'a\nc\na b c',expectedOutput:'2',isHidden:true}]),

p(63,'Rotting Oranges','Medium','Graphs',['BFS','Matrix'],
`Grid: 0=empty, 1=fresh orange, 2=rotten. Each minute, rotten oranges rot adjacent fresh ones. Return minutes to rot all, or -1.`,
'First line: r c. Next r lines: space-separated 0/1/2.','Minutes or -1.',
'1 ≤ r,c ≤ 10',
[{input:'3 3\n2 1 1\n1 1 0\n0 1 1',output:'4'},{input:'3 3\n2 1 1\n0 1 1\n1 0 1',output:'-1'}],
sc('function solution(grid) {\n    // multi-source BFS\n    \n}'),
[{input:'3 3\n2 1 1\n1 1 0\n0 1 1',expectedOutput:'4'},{input:'3 3\n2 1 1\n0 1 1\n1 0 1',expectedOutput:'-1'}],
[{input:'1 1\n0',expectedOutput:'0',isHidden:true}]),

p(64,'Alien Dictionary','Hard','Graphs',['BFS','Topological Sort','String','Graph'],
`Given sorted alien dictionary words, determine the order of characters. Return lexicographic order string.`,
'Space-separated words in alien dictionary order.','Characters in order (no spaces), or "" if invalid.',
'1 ≤ words.length ≤ 100',
[{input:'wrt wrf er ett rftt',output:'wertf'},{input:'z x',output:'zx'}],
sc(jsArr('build graph from adjacent words')),
[{input:'wrt wrf er ett rftt',expectedOutput:'wertf'},{input:'z x',expectedOutput:'zx'}],
[{input:'z z',expectedOutput:'',isHidden:true}]),

/* ═══════════════════ DYNAMIC PROGRAMMING 65-76 ═══════════════════ */
p(65,'Climbing Stairs','Easy','Dynamic Programming',['Math','Memoization','DP'],
`You can climb 1 or 2 steps at a time. How many distinct ways to reach step n?`,
'A single integer n.','Number of ways.',
'1 ≤ n ≤ 45',
[{input:'2',output:'2'},{input:'3',output:'3'}],
sc('function solution(n) {\n    // fibonacci DP\n    \n}'),
[{input:'2',expectedOutput:'2'},{input:'3',expectedOutput:'3'}],
[{input:'1',expectedOutput:'1',isHidden:true},{input:'5',expectedOutput:'8',isHidden:true}]),

p(66,'House Robber','Medium','Dynamic Programming',['Array','DP'],
`Rob houses in a row — cannot rob adjacent houses. Maximise amount.`,
'Space-separated non-negative integers.','Maximum robbed amount.',
'1 ≤ n ≤ 100, 0 ≤ nums[i] ≤ 400',
[{input:'1 2 3 1',output:'4'},{input:'2 7 9 3 1',output:'12'}],
sc(jsArr('dp[i] = max(dp[i-2]+nums[i], dp[i-1])')),
[{input:'1 2 3 1',expectedOutput:'4'},{input:'2 7 9 3 1',expectedOutput:'12'}],
[{input:'0',expectedOutput:'0',isHidden:true},{input:'1 3 1 3 100',expectedOutput:'103',isHidden:true}]),

p(67,'Coin Change','Medium','Dynamic Programming',['Array','DP','BFS'],
`Find minimum number of coins to make \`amount\`. Return -1 if impossible.`,
'First line: space-separated coin denominations. Second line: amount.','Minimum coins or -1.',
'1 ≤ coins.length ≤ 12, 0 ≤ amount ≤ 10^4',
[{input:'1 5 6 9\n11',output:'2'},{input:'2\n3',output:'-1'}],
sc(jsTwoArr('DP bottom-up')),
[{input:'1 5 6 9\n11',expectedOutput:'2'},{input:'2\n3',expectedOutput:'-1'}],
[{input:'1\n0',expectedOutput:'0',isHidden:true},{input:'1 2 5\n11',expectedOutput:'3',isHidden:true}]),

p(68,'Longest Increasing Subsequence','Medium','Dynamic Programming',['Array','DP','Binary Search'],
`Find the length of the longest strictly increasing subsequence.`,
'Space-separated integers.','Length of LIS.',
'1 ≤ n ≤ 2500, -10^4 ≤ nums[i] ≤ 10^4',
[{input:'10 9 2 5 3 7 101 18',output:'4'},{input:'0 1 0 3 2 3',output:'4'}],
sc(jsArr('DP or patience sorting')),
[{input:'10 9 2 5 3 7 101 18',expectedOutput:'4'},{input:'0 1 0 3 2 3',expectedOutput:'4'}],
[{input:'7 7 7 7 7',expectedOutput:'1',isHidden:true}]),

p(69,'Unique Paths','Medium','Dynamic Programming',['Math','DP','Combinatorics'],
`Robot starts top-left, can move right or down, count paths to bottom-right of m×n grid.`,
'Two integers m and n.','Number of unique paths.',
'1 ≤ m,n ≤ 100',
[{input:'3 7',output:'28'},{input:'3 2',output:'3'}],
sc('function solution(m, n) {\n    // DP grid\n    \n}'),
[{input:'3 7',expectedOutput:'28'},{input:'3 2',expectedOutput:'3'}],
[{input:'1 1',expectedOutput:'1',isHidden:true},{input:'7 3',expectedOutput:'28',isHidden:true}]),

p(70,'Edit Distance','Hard','Dynamic Programming',['String','DP'],
`Return the minimum operations (insert, delete, replace) to convert \`word1\` to \`word2\`.`,
'Two strings on separate lines.','Minimum edit distance.',
'0 ≤ word.length ≤ 500, lowercase English',
[{input:'horse\nros',output:'3'},{input:'intention\nexecution',output:'5'}],
sc(jsTwoStr('2D DP table')),
[{input:'horse\nros',expectedOutput:'3'},{input:'intention\nexecution',expectedOutput:'5'}],
[{input:'\n',expectedOutput:'0',isHidden:true},{input:'a\nb',expectedOutput:'1',isHidden:true}]),

p(71,'Longest Common Subsequence','Medium','Dynamic Programming',['String','DP'],
`Return the length of the longest common subsequence of two strings.`,
'Two strings on separate lines.','LCS length.',
'1 ≤ text.length ≤ 1000, lowercase English',
[{input:'abcde\nace',output:'3'},{input:'abc\nabc',output:'3'}],
sc(jsTwoStr('2D DP')),
[{input:'abcde\nace',expectedOutput:'3'},{input:'abc\nabc',expectedOutput:'3'}],
[{input:'abc\ndef',expectedOutput:'0',isHidden:true}]),

p(72,'Word Break','Medium','Dynamic Programming',['String','DP','Trie','Memoization'],
`Return true if \`s\` can be segmented into words from \`wordDict\`.`,
'First line: string s. Second line: space-separated wordDict.','true or false.',
'1 ≤ s.length ≤ 300, 1 ≤ wordDict.length ≤ 1000',
[{input:'leetcode\nleet code',output:'true'},{input:'applepenapple\napple pen',output:'true'},{input:'catsandog\ncats dog sand and cat',output:'false'}],
sc(jsTwoStr('DP with set lookup')),
[{input:'leetcode\nleet code',expectedOutput:'true'},{input:'catsandog\ncats dog sand and cat',expectedOutput:'false'}],
[{input:'a\na',expectedOutput:'true',isHidden:true}]),

p(73,'Maximum Product Subarray','Medium','Dynamic Programming',['Array','DP'],
`Find the contiguous subarray with the largest product.`,
'Space-separated integers.','Maximum product.',
'1 ≤ n ≤ 2×10^4, -10 ≤ nums[i] ≤ 10',
[{input:'2 3 -2 4',output:'6'},{input:'-2 0 -1',output:'0'}],
sc(jsArr('track maxProd and minProd')),
[{input:'2 3 -2 4',expectedOutput:'6'},{input:'-2 0 -1',expectedOutput:'0'}],
[{input:'-2',expectedOutput:'-2',isHidden:true},{input:'2 -5 -2 -4 3',expectedOutput:'24',isHidden:true}]),

p(74,'Jump Game','Medium','Dynamic Programming',['Array','DP','Greedy'],
`Each element is max jump length. Return true if you can reach the last index.`,
'Space-separated non-negative integers.','true or false.',
'1 ≤ n ≤ 3×10^4',
[{input:'2 3 1 1 4',output:'true'},{input:'3 2 1 0 4',output:'false'}],
sc(jsArr('track max reachable')),
[{input:'2 3 1 1 4',expectedOutput:'true'},{input:'3 2 1 0 4',expectedOutput:'false'}],
[{input:'0',expectedOutput:'true',isHidden:true}]),

p(75,'Partition Equal Subset Sum','Medium','Dynamic Programming',['Array','DP'],
`Return true if the array can be partitioned into two subsets with equal sum.`,
'Space-separated positive integers.','true or false.',
'1 ≤ n ≤ 200, 1 ≤ nums[i] ≤ 100',
[{input:'1 5 11 5',output:'true'},{input:'1 2 3 5',output:'false'}],
sc(jsArr('0/1 knapsack DP')),
[{input:'1 5 11 5',expectedOutput:'true'},{input:'1 2 3 5',expectedOutput:'false'}],
[{input:'1 1',expectedOutput:'true',isHidden:true}]),

p(76,'Distinct Subsequences','Hard','Dynamic Programming',['String','DP'],
`Count distinct subsequences of string \`s\` that equal string \`t\`.`,
'Two strings on separate lines (s then t).','Count of distinct subsequences.',
'1 ≤ s.length ≤ 1000, 1 ≤ t.length ≤ 1000, lowercase English',
[{input:'rabbbit\nrabbit',output:'3'},{input:'babgbag\nbag',output:'5'}],
sc(jsTwoStr('2D DP')),
[{input:'rabbbit\nrabbit',expectedOutput:'3'},{input:'babgbag\nbag',expectedOutput:'5'}],
[{input:'a\na',expectedOutput:'1',isHidden:true}]),

/* ═══════════════════ SORTING / SEARCHING / HEAP 77-84 ═══════════════════ */
p(77,'Sort Colors','Medium','Sorting',['Array','Two Pointers','Sorting'],
`Sort an array of 0s, 1s, 2s in-place (Dutch National Flag).`,
'Space-separated integers (only 0,1,2).','Sorted array.',
'1 ≤ n ≤ 300',
[{input:'2 0 2 1 1 0',output:'0 0 1 1 2 2'},{input:'2 0 1',output:'0 1 2'}],
sc(jsArr('three-pointer DNF')),
[{input:'2 0 2 1 1 0',expectedOutput:'0 0 1 1 2 2'},{input:'2 0 1',expectedOutput:'0 1 2'}],
[{input:'0',expectedOutput:'0',isHidden:true}]),

p(78,'Kth Largest Element','Medium','Sorting',['Array','Sorting','Heap','Quickselect'],
`Find the kth largest element in an unsorted array.`,
'First line: space-separated integers. Second line: k.','The kth largest element.',
'1 ≤ k ≤ n ≤ 10^4',
[{input:'3 2 1 5 6 4\n2',output:'5'},{input:'3 2 3 1 2 4 5 5 6\n4',output:'4'}],
sc(jsTwoArr('quickselect or heap')),
[{input:'3 2 1 5 6 4\n2',expectedOutput:'5'},{input:'3 2 3 1 2 4 5 5 6\n4',expectedOutput:'4'}],
[{input:'1\n1',expectedOutput:'1',isHidden:true}]),

p(79,'Top K Frequent Elements','Medium','Heap',['Array','Hash Table','Sorting','Heap','Bucket Sort'],
`Return the k most frequent elements in any order.`,
'First line: space-separated integers. Second line: k.','k most frequent elements, space-separated (sorted ascending).',
'1 ≤ k ≤ unique elements ≤ 10^5',
[{input:'1 1 1 2 2 3\n2',output:'1 2'},{input:'1\n1',output:'1'}],
sc(jsTwoArr('frequency map then sort')),
[{input:'1 1 1 2 2 3\n2',expectedOutput:'1 2'},{input:'1\n1',expectedOutput:'1'}],
[{input:'4 1 -1 2 -1 2 3\n2',expectedOutput:'-1 2',isHidden:true}]),

p(80,'Merge K Sorted Lists','Hard','Heap',['Linked List','Divide and Conquer','Heap','Merge Sort'],
`Merge k sorted lists. Input: k lines each with sorted space-separated integers.`,
'First line: k. Next k lines: sorted space-separated integers.','Single merged sorted list.',
'0 ≤ k ≤ 10^4, 0 ≤ nodes ≤ 500',
[{input:'3\n1 4 5\n1 3 4\n2 6',output:'1 1 2 3 4 4 5 6'},{input:'0',output:''}],
sc('function solution(lists) {\n    // priority queue / merge sort\n    \n}'),
[{input:'3\n1 4 5\n1 3 4\n2 6',expectedOutput:'1 1 2 3 4 4 5 6'},{input:'0',expectedOutput:''}],
[{input:'1\n',expectedOutput:'',isHidden:true}]),

p(81,'Find Median from Data Stream','Hard','Heap',['Sorting','Heap','Design'],
`Simulate adding numbers and finding median. Input: list of numbers added in order.`,
'Space-separated integers added one by one.','Median after ALL are added (1 decimal).',
'1 ≤ n ≤ 5×10^4',
[{input:'1 2',output:'1.5'},{input:'1 2 3',output:'2.0'}],
sc(jsArr('two heaps: max-heap left, min-heap right')),
[{input:'1 2',expectedOutput:'1.5'},{input:'1 2 3',expectedOutput:'2.0'}],
[{input:'6',expectedOutput:'6.0',isHidden:true}]),

p(82,'Meeting Rooms II','Medium','Heap',['Array','Greedy','Sorting','Heap'],
`Given meeting time intervals, find the minimum number of conference rooms required.`,
'Each line: start end. Last line: END.','Minimum rooms.',
'1 ≤ intervals.length ≤ 10^4',
[{input:'0 30\n5 10\n15 20\nEND',output:'2'},{input:'7 10\n2 4\nEND',output:'1'}],
sc('function solution(intervals) {\n    // sort start, min-heap for end times\n    \n}'),
[{input:'0 30\n5 10\n15 20\nEND',expectedOutput:'2'},{input:'7 10\n2 4\nEND',expectedOutput:'1'}],
[{input:'1 10\n2 7\n3 19\n8 12\n10 20\n11 30\nEND',expectedOutput:'4',isHidden:true}]),

p(83,'Merge Intervals','Medium','Sorting',['Array','Sorting'],
`Merge all overlapping intervals.`,
'Each line: start end. Last line: END.','Merged intervals, one per line.',
'1 ≤ intervals.length ≤ 10^4',
[{input:'1 3\n2 6\n8 10\n15 18\nEND',output:'1 6\n8 10\n15 18'},{input:'1 4\n4 5\nEND',output:'1 5'}],
sc('function solution(intervals) {\n    // sort by start, merge overlapping\n    \n}'),
[{input:'1 3\n2 6\n8 10\n15 18\nEND',expectedOutput:'1 6\n8 10\n15 18'},{input:'1 4\n4 5\nEND',expectedOutput:'1 5'}],
[{input:'1 4\n0 4\nEND',expectedOutput:'0 4',isHidden:true}]),

p(84,'Task Scheduler','Medium','Heap',['Array','Greedy','Sorting','Heap','Counting'],
`Given tasks and cooldown n, return minimum time to finish all tasks.`,
'First line: tasks (space-separated chars). Second line: n.','Minimum time.',
'1 ≤ tasks.length ≤ 10^4, 0 ≤ n ≤ 100',
[{input:'A A A B B B\n2',output:'8'},{input:'A A A B B B\n0',output:'6'}],
sc('function solution(tasks, n) {\n    // freq count + greedy\n    \n}'),
[{input:'A A A B B B\n2',expectedOutput:'8'},{input:'A A A B B B\n0',expectedOutput:'6'}],
[{input:'A A A A B B C\n2',expectedOutput:'7',isHidden:true}]),

/* ═══════════════════ BACKTRACKING 85-90 ═══════════════════ */
p(85,'Subsets','Medium','Backtracking',['Array','Backtracking','Bit Manipulation'],
`Return all possible subsets (power set). Output each subset sorted, one per line.`,
'Space-separated unique integers.','All subsets, one per line (sorted), ordered lexicographically.',
'1 ≤ n ≤ 10, all unique',
[{input:'1 2 3',output:'\n1\n1 2\n1 2 3\n1 3\n2\n2 3\n3'}],
sc(jsArr('backtracking include/exclude')),
[{input:'1 2 3',expectedOutput:'\n1\n1 2\n1 2 3\n1 3\n2\n2 3\n3'}],
[{input:'0',expectedOutput:'\n0',isHidden:true}]),

p(86,'Permutations','Medium','Backtracking',['Array','Backtracking'],
`Return all permutations of distinct integers, one per line.`,
'Space-separated unique integers.','All permutations, one per line, space-separated.',
'1 ≤ n ≤ 6, all unique',
[{input:'1 2 3',output:'1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1'}],
sc(jsArr('backtracking with visited set')),
[{input:'1 2 3',expectedOutput:'1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1'}],
[{input:'0 1',expectedOutput:'0 1\n1 0',isHidden:true}]),

p(87,'Combination Sum','Medium','Backtracking',['Array','Backtracking'],
`Find all unique combinations that sum to \`target\` using elements from \`candidates\` (reuse allowed). Each combination sorted.`,
'First line: space-separated candidates. Second line: target.','Each combination on a line.',
'1 ≤ candidates.length ≤ 30, 2 ≤ target ≤ 40, candidates distinct 2-40',
[{input:'2 3 6 7\n7',output:'2 2 3\n7'},{input:'2 3 5\n8',output:'2 2 2 2\n2 3 3\n3 5'}],
sc(jsTwoArr('backtracking with start index')),
[{input:'2 3 6 7\n7',expectedOutput:'2 2 3\n7'},{input:'2 3 5\n8',expectedOutput:'2 2 2 2\n2 3 3\n3 5'}],
[{input:'2\n1',expectedOutput:'',isHidden:true}]),

p(88,'N-Queens','Hard','Backtracking',['Array','Backtracking'],
`Place N queens on N×N board so no two attack. Return number of solutions.`,
'A single integer n.','Number of distinct solutions.',
'1 ≤ n ≤ 9',
[{input:'4',output:'2'},{input:'1',output:'1'}],
sc('function solution(n) {\n    // backtrack with col/diag sets\n    \n}'),
[{input:'4',expectedOutput:'2'},{input:'1',expectedOutput:'1'}],
[{input:'5',expectedOutput:'10',isHidden:true},{input:'8',expectedOutput:'92',isHidden:true}]),

p(89,'Generate Parentheses','Medium','Backtracking',['String','Backtracking','DP'],
`Generate all combinations of n pairs of well-formed parentheses.`,
'A single integer n.','All valid combinations, one per line, lexicographically sorted.',
'1 ≤ n ≤ 8',
[{input:'3',output:'((()))\n(()())\n(())()\n()(())\n()()()'},{input:'1',output:'()'}],
sc('function solution(n) {\n    // backtrack with open/close counts\n    \n}'),
[{input:'3',expectedOutput:'((()))\n(()())\n(())()\n()(())\n()()()'},{input:'1',expectedOutput:'()'}],
[{input:'2',expectedOutput:'(())\n()()',isHidden:true}]),

p(90,'Sudoku Solver','Hard','Backtracking',['Array','Backtracking','Matrix'],
`Solve a Sudoku puzzle. Input: 9 lines of 9 digits (0 = empty cell).`,
'9 lines of 9 space-separated digits (0=empty).','Solved board (9 lines of 9 digits).',
'Input always has exactly one solution',
[{input:'5 3 0 0 7 0 0 0 0\n6 0 0 1 9 5 0 0 0\n0 9 8 0 0 0 0 6 0\n8 0 0 0 6 0 0 0 3\n4 0 0 8 0 3 0 0 1\n7 0 0 0 2 0 0 0 6\n0 6 0 0 0 0 2 8 0\n0 0 0 4 1 9 0 0 5\n0 0 0 0 8 0 0 7 9',output:'5 3 4 6 7 8 9 1 2\n6 7 2 1 9 5 3 4 8\n1 9 8 3 4 2 5 6 7\n8 5 9 7 6 1 4 2 3\n4 2 6 8 5 3 7 9 1\n7 1 3 9 2 4 8 5 6\n9 6 1 5 3 7 2 8 4\n2 8 7 4 1 9 6 3 5\n3 4 5 2 8 6 1 7 9'}],
sc('function solution(board) {\n    // backtrack with row/col/box sets\n    \n}'),
[{input:'5 3 0 0 7 0 0 0 0\n6 0 0 1 9 5 0 0 0\n0 9 8 0 0 0 0 6 0\n8 0 0 0 6 0 0 0 3\n4 0 0 8 0 3 0 0 1\n7 0 0 0 2 0 0 0 6\n0 6 0 0 0 0 2 8 0\n0 0 0 4 1 9 0 0 5\n0 0 0 0 8 0 0 7 9',expectedOutput:'5 3 4 6 7 8 9 1 2\n6 7 2 1 9 5 3 4 8\n1 9 8 3 4 2 5 6 7\n8 5 9 7 6 1 4 2 3\n4 2 6 8 5 3 7 9 1\n7 1 3 9 2 4 8 5 6\n9 6 1 5 3 7 2 8 4\n2 8 7 4 1 9 6 3 5\n3 4 5 2 8 6 1 7 9'}],
[]),

/* ═══════════════════ BIT MANIPULATION / MATH / GREEDY 91-100 ═══════════════════ */
p(91,'Number of 1 Bits','Easy','Bit Manipulation',['Bit Manipulation'],
`Count the number of 1 bits in the binary representation of n (Hamming weight).`,
'A non-negative integer.','Number of 1 bits.',
'0 ≤ n < 2^31',
[{input:'11',output:'3'},{input:'128',output:'1'}],
sc('function solution(n) {\n    // n & (n-1) trick\n    \n}'),
[{input:'11',expectedOutput:'3'},{input:'128',expectedOutput:'1'}],
[{input:'0',expectedOutput:'0',isHidden:true},{input:'2147483645',expectedOutput:'29',isHidden:true}]),

p(92,'Power of Two','Easy','Bit Manipulation',['Math','Bit Manipulation','Recursion'],
`Return true if n is a power of two.`,
'An integer n.','true or false.',
'-2^31 ≤ n ≤ 2^31 - 1',
[{input:'1',output:'true'},{input:'16',output:'true'},{input:'3',output:'false'}],
sc('function solution(n) {\n    // n > 0 && (n & n-1) === 0\n    \n}'),
[{input:'1',expectedOutput:'true'},{input:'3',expectedOutput:'false'}],
[{input:'0',expectedOutput:'false',isHidden:true},{input:'4',expectedOutput:'true',isHidden:true}]),

p(93,'Reverse Bits','Easy','Bit Manipulation',['Bit Manipulation','Divide and Conquer'],
`Reverse bits of a 32-bit unsigned integer.`,
'A non-negative integer.','Reversed bits as unsigned integer.',
'0 ≤ n < 2^32',
[{input:'43261596',output:'964176192'},{input:'4294967293',output:'3221225471'}],
sc('function solution(n) {\n    // bit by bit reversal\n    \n}'),
[{input:'43261596',expectedOutput:'964176192'}],
[{input:'0',expectedOutput:'0',isHidden:true}]),

p(94,'Sum of Two Integers','Medium','Bit Manipulation',['Math','Bit Manipulation'],
`Calculate sum of two integers without using + or - operators.`,
'Two integers a and b on one line.','Their sum.',
'-1000 ≤ a, b ≤ 1000',
[{input:'1 2',output:'3'},{input:'-2 3',output:'1'}],
sc('function solution(a, b) {\n    // XOR + carry with AND\n    \n}'),
[{input:'1 2',expectedOutput:'3'},{input:'-2 3',expectedOutput:'1'}],
[{input:'0 0',expectedOutput:'0',isHidden:true}]),

p(95,'Fibonacci Number','Easy','Recursion',['Math','Recursion','Memoization','DP'],
`Return the Nth Fibonacci number. F(0)=0, F(1)=1.`,
'A non-negative integer n.','F(n).',
'0 ≤ n ≤ 30',
[{input:'2',output:'1'},{input:'3',output:'2'},{input:'4',output:'3'}],
sc('function solution(n) {\n    // memoization or iterative\n    \n}'),
[{input:'2',expectedOutput:'1'},{input:'3',expectedOutput:'2'}],
[{input:'0',expectedOutput:'0',isHidden:true},{input:'10',expectedOutput:'55',isHidden:true}]),

p(96,'Jump Game II','Medium','Greedy',['Array','Greedy','DP'],
`Find minimum jumps to reach the last index.`,
'Space-separated non-negative integers.','Minimum number of jumps.',
'1 ≤ n ≤ 10^4, always reachable',
[{input:'2 3 1 1 4',output:'2'},{input:'2 3 0 1 4',output:'2'}],
sc(jsArr('greedy: track farthest reachable')),
[{input:'2 3 1 1 4',expectedOutput:'2'},{input:'2 3 0 1 4',expectedOutput:'2'}],
[{input:'1',expectedOutput:'0',isHidden:true}]),

p(97,'Gas Station','Medium','Greedy',['Array','Greedy'],
`n gas stations in a circle. Gas[i] at station i, cost[i] to travel to next. Find starting station index; return -1 if impossible.`,
'First line: gas amounts. Second line: costs.','Starting index or -1.',
'1 ≤ n ≤ 10^5, gas[i], cost[i] ≥ 0',
[{input:'1 2 3 4 5\n3 4 5 1 2',output:'3'},{input:'2 3 4\n3 4 3',output:'-1'}],
sc('function solution(gas, cost) {\n    // greedy starting point\n    \n}'),
[{input:'1 2 3 4 5\n3 4 5 1 2',expectedOutput:'3'},{input:'2 3 4\n3 4 3',expectedOutput:'-1'}],
[{input:'5 8 2 8\n6 5 6 6',expectedOutput:'3',isHidden:true}]),

p(98,'Group Anagrams','Medium','Hashing',['Array','Hash Table','String','Sorting'],
`Group an array of strings into anagrams. Return size of each group, sorted ascending.`,
'Space-separated strings.','Group sizes sorted ascending.',
'1 ≤ strs.length ≤ 10^4, 0 ≤ strs[i].length ≤ 100',
[{input:'eat tea tan ate nat bat',output:'1 2 3'},{input:'',output:'1'}],
sc(jsArr('sort each word as key')),
[{input:'eat tea tan ate nat bat',expectedOutput:'1 2 3'}],
[{input:'a',expectedOutput:'1',isHidden:true}]),

p(99,'Minimum Window Substring','Hard','Sliding Window',['String','Sliding Window','Hash Table'],
`Find the minimum window substring of \`s\` that contains all characters of \`t\`.`,
'Two strings on separate lines (s then t).','Minimum window or "".',
'1 ≤ s.length ≤ 10^5, 1 ≤ t.length ≤ 10^4',
[{input:'ADOBECODEBANC\nABC',output:'BANC'},{input:'a\na',output:'a'},{input:'a\naa',output:''}],
sc(jsTwoStr('sliding window with freq maps')),
[{input:'ADOBECODEBANC\nABC',expectedOutput:'BANC'},{input:'a\na',expectedOutput:'a'}],
[{input:'a\naa',expectedOutput:'',isHidden:true}]),

p(100,'LRU Cache','Medium','Hashing',['Design','Hash Table','Linked List','Doubly-Linked List'],
`Design and simulate an LRU Cache. Input: capacity, then operations "PUT key val" or "GET key". Output -1 on miss.`,
'First line: capacity. Following lines: GET key or PUT key val. Last line: END.','Output for each GET on separate lines.',
'1 ≤ capacity ≤ 3000',
[{input:'2\nPUT 1 1\nPUT 2 2\nGET 1\nPUT 3 3\nGET 2\nPUT 4 4\nGET 1\nGET 3\nGET 4\nEND',output:'1\n-1\n-1\n3\n4'}],
sc('function solution(capacity, ops) {\n    // Map for O(1) get, doubly-linked list for O(1) eviction\n    \n}'),
[{input:'2\nPUT 1 1\nPUT 2 2\nGET 1\nPUT 3 3\nGET 2\nPUT 4 4\nGET 1\nGET 3\nGET 4\nEND',expectedOutput:'1\n-1\n-1\n3\n4'}],
[{input:'1\nPUT 2 1\nGET 2\nPUT 3 2\nGET 2\nGET 3\nEND',expectedOutput:'1\n-1\n2',isHidden:true}]),

];

/* ──────────────────────────────────────────
   SEED
────────────────────────────────────────── */
const seedProblems = async () => {
  await connectDB();

  let inserted = 0, skipped = 0;

  for (const prob of problems) {
    const exists = await Problem.findOne({ slug: prob.slug });
    if (exists) { skipped++; continue; }
    await Problem.create(prob);
    inserted++;
  }

  console.log(`✅  DSA seed complete — ${inserted} inserted, ${skipped} skipped (already exist)`);
  process.exit(0);
};

seedProblems().catch((err) => { console.error(err); process.exit(1); });
